'use strict';

export const AUTH0_LOGGED_IN = 'AUTH0_LOGGED_IN';
export const AUTH0_LOGGED_OUT = 'AUTH0_LOGGED_OUT';
export const AUTH0_REFRESH_PROFILE = 'AUTH0_REFRESH_PROFILE';
export const AUTH0_REFRESH_TOKEN = 'AUTH0_REFRESH_TOKEN';

export const CHAT_SCREEN_NEW_MESSAGE = 'CHAT_SCREEN_NEW_MESSAGE';
export const CHAT_SCREEN_PURGE = 'CHAT_SCREEN_PURGE';
export const CHAT_SCREEN_LOAD_EARLIER_SUCCESS = 'CHAT_SCREEN_LOAD_EARLIER_SUCCESS';
export const CHAT_SCREEN_LOAD_EARLIER_LOADING = 'CHAT_SCREEN_LOAD_EARLIER_LOADING';
export const CHAT_SCREEN_LOAD_EARLIER_ERROR = 'CHAT_SCREEN_LOAD_EARLIER_ERROR';