'use strict';

export const AUTH0_LOGGED_IN = 'AUTH0_LOGGED_IN';
export const AUTH0_LOGGED_OUT = 'AUTH0_LOGGED_OUT';
export const AUTH0_REFRESH_PROFILE = 'AUTH0_REFRESH_PROFILE';
export const AUTH0_REFRESH_TOKEN = 'AUTH0_REFRESH_TOKEN';